"""Tests for incy://crypt1 decryption.

Validates the decoder against real links produced by the official
@incy/link-encoder package (https://github.com/INCY-DEV/incy-link-encoder),
plus error-handling paths.
"""

import json

from core.incy import (
    decrypt_link,
    decrypt_text,
    is_incy,
    derive_key,
    KEY_FINGERPRINT,
)

# Real links generated by the official package (see scripts/gen-vectors.mjs).
VECTORS = json.load(open("data/incy_vectors.json"))


def test_decrypt_real_links():
    """Links from the official encoder must decode to the original URL."""
    for v in VECTORS["links"]:
        assert decrypt_link(v["link"]) == v["url"]


def test_is_incy():
    assert is_incy("prefix incy://crypt1/abc def")
    assert not is_incy("https://example.com")
    assert not is_incy("happy://crypt1/abc")


def test_decrypt_text_replaces_all():
    links = VECTORS["links"]
    text = "\n".join(l["link"] for l in links)
    out = decrypt_text(text)
    expected = "\n".join(l["url"] for l in links)
    assert out == expected


def test_key_fingerprint_matches_published_clients():
    """The derived K1 must match the fingerprint shipped in the encoder."""
    assert derive_key() is not None
    assert KEY_FINGERPRINT == VECTORS["keyFingerprint"]


def test_tampered_link_fails():
    link = VECTORS["links"][0]["link"]
    # Flip a character in the middle of the payload (after the scheme prefix)
    # so the AES-GCM tag no longer verifies.
    prefix = "incy://crypt1/"
    payload = link[len(prefix):]
    mid = len(payload) // 2
    ch = payload[mid]
    new_ch = "A" if ch != "A" else "B"
    bad_payload = payload[:mid] + new_ch + payload[mid + 1:]
    bad = prefix + bad_payload
    try:
        decrypt_link(bad)
        assert False, "expected authentication failure"
    except RuntimeError as e:
        assert "authentication failed" in str(e)


def test_short_payload_raises():
    try:
        decrypt_link("incy://crypt1/AAAA")
        assert False
    except RuntimeError as e:
        assert "too short" in str(e)


def test_wrong_prefix_raises():
    try:
        decrypt_link("https://example.com")
        assert False
    except RuntimeError as e:
        assert "prefix" in str(e)
