"""INCY decrypt — decrypt incy://crypt1/<payload> deep links.

Built-in offline decryptor for the @incy/link-encoder format
(https://github.com/INCY-DEV/incy-link-encoder). The AES-256-GCM key
K1 is derived from salt constants + two 4 KiB keymat blobs shipped in
this package — exactly mirroring the published clients, so a link
generated by that package decodes bit-for-bit identically.

Usage:
    decrypt_link(link)   — decrypt a single incy:// link
    decrypt_text(text)   — replace all incy:// links in text
    is_incy(text)        — check if text contains incy:// links
"""

from __future__ import annotations

import base64
import hashlib
import json
import logging
import os
import re

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants (mirror src/index.ts)
# ---------------------------------------------------------------------------

SCHEME = "incy"
HOST = "crypt1"
PREFIX = f"{SCHEME}://{HOST}/"

# Salt parts concatenated in order, fed into the SHA-256 KDF.
_SALT_PARTS = ["incy", "deep", "crypt1", "v2026.06"]

KEYMAT_A_OFFSET = 1024
KEYMAT_B_OFFSET = 2048
KEYMAT_LEN = 32

# SHA-256 of K1 — sanity check that the keymat matches the published clients.
EXPECTED_KEY_FINGERPRINT = (
    "b6bf708471cc90043232967660aade86a50b4e57929db2e53c5fa34db624c08c"
)

VERSION = "1.0.0"
SCHEME_VERSION = "crypt1"
KEY_FINGERPRINT = EXPECTED_KEY_FINGERPRINT

INCY_RE = re.compile(r"incy://crypt([0-9]+)/([^\s]+)")

_keymat_cache: dict[str, bytes] | None = None
_key_cache: bytes | None = None


# ---------------------------------------------------------------------------
# Keymat loading + key derivation
# ---------------------------------------------------------------------------

def _load_keymat() -> dict[str, bytes]:
    """Load the two base64 keymat blobs from data/incy_keymat.json."""
    global _keymat_cache
    if _keymat_cache is not None:
        return _keymat_cache
    path = os.path.join(os.path.dirname(__file__), "..", "data", "incy_keymat.json")
    path = os.path.abspath(path)
    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)
    _keymat_cache = {
        "a": base64.b64decode(raw["KEYMAT_A_B64"]),
        "b": base64.b64decode(raw["KEYMAT_B_B64"]),
    }
    return _keymat_cache


def derive_key() -> bytes:
    """Derive K1 = SHA-256(salt + keymat bytes) and verify its fingerprint."""
    global _key_cache
    if _key_cache is not None:
        return _key_cache
    km = _load_keymat()
    a, b = km["a"], km["b"]
    if len(a) < KEYMAT_A_OFFSET + KEYMAT_LEN or len(b) < KEYMAT_B_OFFSET + KEYMAT_LEN:
        raise RuntimeError("incy: keymat assets are smaller than expected")
    km_a = a[KEYMAT_A_OFFSET: KEYMAT_A_OFFSET + KEYMAT_LEN]
    km_b = b[KEYMAT_B_OFFSET: KEYMAT_B_OFFSET + KEYMAT_LEN]
    seed = b"".join(
        [
            *[p.encode("utf-8") for p in _SALT_PARTS],
            km_a,
            km_b,
        ]
    )
    k = hashlib.sha256(seed).digest()
    fp = hashlib.sha256(k).hexdigest()
    if fp != EXPECTED_KEY_FINGERPRINT:
        raise RuntimeError(
            f"incy: derived K1 fingerprint mismatch "
            f"(expected {EXPECTED_KEY_FINGERPRINT}, got {fp}) — "
            "keymat out of sync with published clients"
        )
    _key_cache = k
    return k


# ---------------------------------------------------------------------------
# Base64url helpers (RFC 4648 §5, no padding)
# ---------------------------------------------------------------------------

def _b64url_encode(buf: bytes) -> str:
    return base64.urlsafe_b64encode(buf).rstrip(b"=").decode("ascii")


def _b64url_decode(s: str) -> bytes:
    padding = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + padding)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_incy(text: str) -> bool:
    """Check if text contains incy:// links."""
    return bool(INCY_RE.search(text))


def decrypt_link(link: str) -> str:
    """Decrypt a single incy://crypt1/<payload> link.

    Returns the embedded subscription URL (string). Raises RuntimeError on
    malformed input or authentication failure.
    """
    if not link or not isinstance(link, str):
        raise RuntimeError("incy: link must be a non-empty string")
    if not link.startswith(PREFIX):
        raise RuntimeError(f"incy: expected {PREFIX} prefix")

    payload = link[len(PREFIX):].strip().rstrip("/")
    if not payload:
        raise RuntimeError("incy: empty payload")

    wire = _b64url_decode(payload)
    # iv (12) + tag (16) + at least 1 ct byte
    if len(wire) < 12 + 16 + 1:
        raise RuntimeError("incy: payload too short")

    iv = wire[:12]
    tag = wire[-16:]
    ct = wire[12:-16]

    key = derive_key()
    aes = AESGCM(key)
    try:
        plaintext = aes.decrypt(iv, ct + tag, None)
    except Exception as e:  # authentication failure / tampering
        raise RuntimeError(f"incy: authentication failed ({e})") from e

    try:
        parsed = json.loads(plaintext.decode("utf-8"))
    except Exception as e:
        raise RuntimeError(f"incy: malformed plaintext ({e})") from e

    url = parsed.get("url")
    if not isinstance(url, str) or not url:
        raise RuntimeError("incy: missing url field")
    return url


def decrypt_text(text: str) -> str:
    """Decrypt all incy:// links in text. Returns text with decrypted URLs."""
    def _replace(m: re.Match) -> str:
        link = m.group(0)
        try:
            return decrypt_link(link)
        except Exception as e:
            logger.warning("Failed to decrypt %s: %s", link[:40], e)
            return link  # keep original on failure

    return INCY_RE.sub(_replace, text)


async def fetch_sub_with_decrypt(url: str, timeout: int = 15) -> str:
    """Fetch content from a URL and decrypt any incy:// links found in the text."""
    import httpx

    async with httpx.AsyncClient(timeout=timeout, follow_redirects=True, verify=False) as client:
        resp = await client.get(url)
        resp.raise_for_status()
        text = resp.text
    return decrypt_text(text)
